version: "3"

services:
  cache:
    image: memcached:alpine
    ports:
      - 11211:11211

  tls_cache:
    build: ./tls_memcached/alpine
    image: tls_memcached:alpine
    ports:
      - 11212:11211
