version: "3"

services:
  cache:
    image: memcached
    ports:
      - 11211:11211

  tls_cache:
    image: memcached
    ports:
      - 11212:11211
    volumes:
      - ./certs/gen:/opt/certs
    command:
      - memcached
      - "-Z"
      - "-o"
      - "ssl_chain_cert=/opt/certs/chain/server-rsa2048.pem"
      - "-o"
      - "ssl_key=/opt/certs/key/server-rsa2048.key"
      - "-o"
      - "ssl_ca_cert=/opt/certs/crt/client-ca-root.crt"
      - "-o"
      - "ssl_verify_mode=1" # 0 (None), 1 (Request), 2 (Require) or 3 (Once)
