version: "3"

networks:
  app-tier:
    driver: bridge

services:
  cache:
    image: memcached
    networks:
      - app-tier
    ports:
      - 11211:11211

  tls_cache:
    build: ./tls_memcached/debian
    image: tls_memcached
    networks:
      - app-tier
    ports:
      - 11212:11211
